### ISSUE TITLE
Docker: Error response from daemon

### ISSUE THREAD

**Issue by celprov** [urmzd/embed-md#1]
Hey @urmzd,
Thanks for creating this Github Action.
I tried to use it but I'm running into an error I was hoping you can help me with.

When executing `Run urmzd/embed-md@v1.0.0` I get the following error :

> /usr/bin/docker run --name c0442643e160ff2544d5f834adbbe709bd189_d0ace6 --label 6c0442 --workdir /github/workspace --rm -e "INPUT_MARKDOWN-FILES" -e "INPUT_COMMIT-MESSAGE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/hcph-protocol/hcph-protocol":"/github/workspace" 6c0442:643e160ff2544d5f834adbbe709bd189  "synchronizing code in data-storage.md" "data-storage.md"
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./src/entrypoint.sh": stat ./src/entrypoint.sh: no such file or directory: unknown.
time="2023-04-19T13:30:21Z" level=error msg="error waiting for container: context canceled"

The yml file I wrote to run the Github action is as follows:

> name: Embed code in markdown
> on:
  push:
    branches:
      - mkdocs
      - fix/refine_PACs_info
jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current repo"
        uses: actions/checkout@v3
      - name: "Run entrypoint script."
        uses: urmzd/embed-md@v1.0.0
        id: "embed-code"
        with:
          markdown-files: "data-storage.md"
          commit-message: "synchronizing code in data-storage.md"

Do you have an idea what's wrong ?

**Comment by urmzd** [comment]
First of all, thank you for creating an issue! This is a bug, the entry-point referenced in the dockerfile is incorrect. I'll be fixing this shortly. See issue #2

**Comment by urmzd** [comment]
Going to leave this open, until you've verified that its working, please use `urmzd/embed-md@v1.0.2`. Cheers, Urmzd

**Comment by celprov** [comment]
Hey @urmzd,
Thank you for the quick response. Unfortunately I'm still running into the same issue while calling `uses: urmzd/embed-md@v1.0.2` (and not changing anything else from the ymal file above) :/

**Comment by urmzd** [comment]
Hi @celprov sorry for the late response, I'll take a look at this on Tuesday and try resolving it. Thank you for your patience! In the meanwhile, you might be able to use the script manually (located in root) as part of your pipeline.

Something along the lines of

```
embed:
  embed-code:
    steps:
      - name: Run build script
        run: ./the-build-script-mentioned-above.sh
        shell: bash
```

**Comment by urmzd** [comment]
@celprov I'm sorry for the wait... 😓 

Though, I've finally come back to it and finished it (if you still want to try it).

```yaml
name: "Example"

on: [release]

jobs:
  embed-example:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current repo"
        uses: actions/checkout@v3
      - name: "Run entrypoint script."
        uses: urmzd/embed-md@v1.3.4
        id: "embed-code"
        with:
          markdown-files: "README.md"
          commit-message: "chore: embed example using self"
          commit-name: Urmzd Mukhammadnaim
          commit-email: <urmzd@noreply.com>
          commit-push: "false"
```
